"""association object CharKnow fixed again3

Revision ID: 3d287f554574
Revises: 3d9074ce022e
Create Date: 2023-12-08 14:20:46.442060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d287f554574'
down_revision = '3d9074ce022e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('char_know', schema=None) as batch_op:
        batch_op.drop_constraint('char_know_subject_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'weapon', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('char_know', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('char_know_subject_id_fkey', 'character', ['subject_id'], ['id'])

    # ### end Alembic commands ###
